blank_issues_enabled: true
contact_links:
  - name: "💡 일반 문의 및 피드백 토론"
    url: "https://github.com/giyeopkim/blue_archive_student_archive/discussions"
    about: "아카이브 프로젝트에 관한 건의사항이나 자유로운 의견을 남겨주세요."
